FROM golang:1.22-alpine as build

RUN apk add --no-cache git

WORKDIR /src 

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build consumer.go

FROM alpine:3.19.0 as runtime
COPY --from=build /src/consumer /app/consumer
COPY --from=build /src/.env /app/.env
CMD [ "/app/consumer" ]